### ISSUE TITLE
updating in Linux causes some problems

### ISSUE THREAD

**Issue by muammar** [gerardo/dotfiles#1]
Hi, 

After updating in my debian your dotfiles, I found these new lines in .zshrc that are causing a little warning:

zshrc:47: command not found: brew

These are the lines involved:

 46 # Autojump                                                                      
 47 if [ -f `brew --prefix`/etc/autojump ]; then                                   
 48   . `brew --prefix`/etc/autojump                                               
 49 fi 

After commenting them the problem was solved. 

Another issue, was the " agnoster" theme. It was not placed in the themes directory when I did a git pull (I'd like to stress I just run a bared git pull), so I had to git clone it. As it is said in the agnoster's github page, you also need power line patched fonts. So I did:

git clone git://gist.github.com/1595572.git powerlinefonts

(I stored them in a desired directory of mine), and then I did a symlink to that directory in /usr/share/fonts. With that, the problem was solved. 

More than this, everything is working perfectly. Keep up the good work :)

**Comment by gerardo** [comment]
These problems should not arise anymore, I migrated the submodules to [Neobundle](https://github.com/Shougo/neobundle.vim). Now that plugin manages the dependencies without using git.
