### ISSUE TITLE
Working directory in gnome-terminal > 3.8

### ISSUE THREAD

**Issue by muammar** [gerardo/dotfiles#4]
Hi, 

I don't know if you are aware of the regressions in recent versions of gnome-terminal. I'd like to name specially the working directory. I found a solution to this issue in where the terminal doesn't remember your last active current directory. To fix it, it is just needed to  add this in .zshrc:

. /etc/profile.d/vte.sh

Do you think it is worthy to add this to your dotfiles? If you consider that it is not, so you can close this bug (sin rencores :)).

**Comment by gerardo** [comment]
Hope this is solved for gnome-terminal, cuz I'm closing this!
